# This file contains the locations of all our data sources, such as MemGraph. It
# also includes authentication information.
#
# On my local machine, I marked this file with the method in
# https://stackoverflow.com/a/39776107. This way, I can configure paths for my
# machine. All paths should be absolute.

data:
  memgraph:
    uri: bolt://localhost:7687
    user: cs229-simplewiki-data
    pass: cs229-simplewiki-data-pw
  embeddings:
    1536: /path/to/text-embeddings-1536.npy
    512: /path/to/text-embeddings-512.npy
    256: /path/to/text-embeddings-256.npy

training-data:
  link-prediction: /path/to/link-prediction/
