# All of the services we host data in. Wikipedia publishes its dumps as MySQL,
# but we do most of our work in Memgraph since it's more useful for our
# workload. Memgraph Lab is a useful interface for prototyping queries.

name: cs229-simplewiki-data
services:

  db-mysql:
    image: mysql:9.1
    environment:
      MYSQL_DATABASE: simplewiki
      MYSQL_ROOT_PASSWORD: cs229-simplewiki-data-rootpw
      MYSQL_USER: cs229-simplewiki-data
      MYSQL_PASSWORD: cs229-simplewiki-data-pw
    command: >-
      --innodb_redo_log_capacity=2G
      --innodb_buffer_pool_size=2G
      --secure-file-priv="/xfer/"
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/xfer:/xfer

  db-memgraph:
    image: memgraph/memgraph-mage:1.20-memgraph-2.20
    environment:
      MEMGRAPH_USER: cs229-simplewiki-data
      MEMGRAPH_PASSWORD: cs229-simplewiki-data-pw
    command: >-
      --storage-mode=IN_MEMORY_ANALYTICAL
      --log-level=INFO
      --memory-limit=24576
    ports:
      - 7687:7687
      - 7444:7444
    volumes:
      - ./data/memgraph/data:/var/lib/memgraph
      - ./data/memgraph/xfer:/xfer

  iface-memgraph-lab:
    image: memgraph/lab:2.17.0
    ports:
      - 3000:3000
